### ISSUE TITLE
make allyesconfig errors makefile:133, 375, 26 

### ISSUE THREAD

**Issue by tokenativo** [deeptho/blindscan#1]
$ uname -a
Linux oasis 5.4.0-1046-raspi #50-Ubuntu SMP PREEMPT Thu Oct 28 05:32:10 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

/tbsdriver/media_build$ make allyesconfig
make -C /home/user/tbsdriver/media_build/v4l allyesconfig
make[1]: Entering directory '/home/user/tbsdriver/media_build/v4l'
No version yet, using 5.4.0-1046-raspi
make[2]: Entering directory '/home/user/tbsdriver/media_build/linux'
Syncing with dir ../../media
Applying patches for kernel 5.4.0-1046-raspi
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
patch -s -f -N -p1 -i ../backports/debug.patch
patch -s -f -N -p1 -i ../backports/drx39xxj.patch
patch -s -f -N -p1 -i ../backports/ccs.patch
patch -s -f -N -p1 -i ../backports/rc-cec.patch
patch -s -f -N -p1 -i **../backports/v5.14_bus_void_return.patch
1 out of 1 hunk FAILED
make[2]: *** [Makefile:133: apply_patches] Error 1
make[2]: Leaving directory '/home/user/tbsdriver/media_build/linux'
make[1]: *** [Makefile:375: allyesconfig] Error 2
make[1]: Leaving directory '/home/user/tbsdriver/media_build/v4l'
make: *** [Makefile:26: allyesconfig] Error 2
user@oasis:~/tbsdriver/media_build$**

**Comment by deeptho** [comment]
That is a media_build problem unfortunately and unrelated to the drivers themselves. 
ee teh README for a kernel version that works.

With experimenting with different version of media_build you might find a solution. Try checking out older or newer versions of media_build.

**Comment by psyborg55** [comment]
same here, on x86_64 (20.04.3 LTS). i tried to use tune util only with default kernel driver, got this:

`em28xx 2-2:1.0: dtv_property_process_set: SET cmd 0x0000004a undefined`

neumo-tune is suppose to support all drivers and this is only due to kernel mismatch, or something else is going on with em28xx ?

**Comment by deeptho** [comment]
Neumo-tune is made to test the blindscan drivers. It is not meant to support all drivers, altought it would not be difficult to do that

**Comment by psyborg55** [comment]
managed to build drivers tree, however the error appears to be related to missing command parameters algo and delsys. device was able to tune (m88ds3103)

**Comment by deeptho** [comment]
Ok. That is good news. The code's error reporting could be improved.

**Comment by deeptho** [comment]
M88rs6060 support is now present.
