### ISSUE TITLE
not working now

### ISSUE THREAD

**Issue by xhiksi** [deeptho/blindscan#3]
I think that actually this app is not working. I have a 6903X on debian 11 64bit its kernel 5.10.0.17 and neumo-blindscan does not pass ioctl extended info line 879: _FE_GET_EXTENDED_INFO failed: blindscan drivers probably not installed_
This is due to different definitions of  struct  'dvb_frontend_extended_info' in frontend.h with the same in neumofrontend.h(the first one has more fields and one missing), and so the define macro FE_GET_EXTENDED_INFO of dvb-core.ko is expanded with different value from same of neumofrontend.h. In this way I have a kernel warning: _dvb_frontend: dvb_frontend_handle_ioctl:3484: unsupported ioctl_
Having a look in dvb_frontend.c:3484, we can see the switch statement hits the case default instead of case FE_GET_EXTENDED_INFO some lines above.
I made struct  'dvb_frontend_extended_info' in neuofrontend.h equal of it in frontend.h, and this step is passed, but program crashes and there is kernel panic:
_[ 4230.188368] INFO: task kdvb-ad-1-fe-0:1258 blocked for more than 120 seconds.
[ 4230.188375]       Tainted: G           OE     5.10.0-17-amd64 #1 Debian 5.10.136-1
[ 4230.188377] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4230.188380] task:kdvb-ad-1-fe-0  state:D stack:    0 pid: 1258 ppid:     2 flags:0x00004000
[ 4230.188384] Call Trace:
[ 4230.188394]  __schedule+0x282/0x880
[ 4230.188398]  schedule+0x46/0xb0
[ 4230.188402]  schedule_preempt_disabled+0xa/0x10
[ 4230.188405]  __mutex_lock.constprop.0+0x133/0x470
[ 4230.188409]  ? desc_read_finalized_seq+0x2f/0x90
[ 4230.188412]  ? _prb_read_valid+0x232/0x2b0
[ 4230.188422]  get_spectrum_scan_fft+0xfe/0x1a0 [stid135]
[ 4230.188427]  ? update_load_avg+0x7a/0x5d0
[ 4230.188431]  ? enqueue_entity+0x163/0x760
[ 4230.188434]  ? sched_clock+0x5/0x10
[ 4230.188437]  ? sched_clock_cpu+0xc/0xb0
[ 4230.188440]  ? record_times+0x15/0x90
[ 4230.188442]  ? psi_group_change+0x41/0x220
[ 4230.188446]  ? __switch_to_asm+0x42/0x80
[ 4230.188449]  ? __switch_to+0x114/0x460
[ 4230.188456]  stid135_spectral_scan_start+0x23/0x40 [stid135]
[ 4230.188461]  stid135_scan_sat+0x4c/0x70 [stid135]
[ 4230.188472]  dvb_frontend_thread+0x481/0x7f0 [dvb_core]
[ 4230.188481]  ? dvb_frontend_swzigzag+0x370/0x370 [dvb_core]
[ 4230.188484]  kthread+0x11b/0x140
[ 4230.188487]  ? __kthread_bind_mask+0x60/0x60
[ 4230.188490]  ret_from_fork+0x22/0x30_

**Comment by deeptho** [comment]
Well, if you did not install the blindscan drivers, then indeed the program will not and cannot work....

So install them first. They are on github.
