### ISSUE TITLE
Blindscan driver check is contradictory

### ISSUE THREAD

**Issue by andimik** [deeptho/blindscan#8]
Seems at the start there is a check if the blindscan drivers are installed. But this is contradictory in my case.

```
Blindscan drivers found
FE_GET_EXTENDED_INFO failed: blindscan drivers probably not installed
Blindscan not supported
```

I'm using https://github.com/deeptho/media_build/commit/cac79e6921c1a7258142e9ddcb2c7734bbcade5b for the media_build 
and https://github.com/deeptho/linux_media/commit/19e872f01a1a5c77b92bd8e71c80dcff5221c8ed for the media with my 6903x.

**Comment by deeptho** [comment]
You are probably using the wrong card? One without blindscan support.

**Comment by andimik** [comment]
If 6903xv1 is really not supported, I'll try 5927 in the next days. Both work with Blindscan under Windows, BTW.

**Comment by deeptho** [comment]
tbs6903Xv1 really IS supported. 
Satesco is using it (or the v2 card - makes no difference)
You will need some debugging.

**Comment by andimik** [comment]
After more than one year I've reinstalled my PC with Ubuntu 24.04 and it works now. Closing.
